version: "3.1"

volumes:
  scripts-teste: {}

services:
  sme-postgres:
    container_name: sme-postgres-testes
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./scripts/postgres/init:/docker-entrypoint-initdb.d/:Z
      - scripts-teste:/opt/scripts:Z
    networks:
      - sme-network
networks:
  sme-network:
    driver: bridge
