version: "3.1"

volumes:
  scripts: {}

services:
  sme-apieol-worker:
    container_name: sme-apieol-worker-testes
    image: registry.sme.prefeitura.sp.gov.br/sgp/sme-pedagogico-worker:dev
    restart: on-failure:10
    ports:
      - '5004:80'
    env_file:
      - sme-api.env
    networks:
      - sme-network
networks:
  sme-network:
    driver: bridge
