version: "3.1"

volumes:
  scripts: {}

services:
  sme-api-eol:
    container_name: sme-apieol-testes
    image: registry.sme.prefeitura.sp.gov.br/sgp/sme-pedagogicowebapi-backend:dev
    restart: on-failure:10
    ports:
      - '5003:80'
    env_file:
      - sme-api.env
    networks:
      - sme-network
networks:
  sme-network:
    driver: bridge
