version: "3.1"

volumes:
  scripts: {}

services:
  sme-worker-service:
    container_name: sme-worker-service-testes
    image: registry.sme.prefeitura.sp.gov.br/sgp/sme-workerservice:dev
    restart: on-failure:10
    ports:
      - '5002:80'
    env_file:
      - sme-api.env
    networks:
      - sme-network
networks:
  sme-network:
    driver: bridge
