version: "3.1"

volumes:
  scripts: {}

services:
  sme-sgp-api:
    container_name: sme-sgp-api-testes
    image: registry.sme.prefeitura.sp.gov.br/sgp/sme-sgp-backend:dev
    restart: on-failure:10
    ports:
      - '5000:80'
    env_file:
      - sme-api.env
    networks:
      - sme-network
networks:
  sme-network:
    driver: bridge
