version: "3.1"

volumes:
  scripts: {}

services:
  sme-worker-rabbit:
    container_name: sme-worker-rabbit-testes
    image: registry.sme.prefeitura.sp.gov.br/sgp/sme-worker-rabbit:dev
    restart: on-failure:10
    ports:
      - '5001:80'
    env_file:
      - sme-api.env
    networks:
      - sme-network
networks:
  sme-network:
    driver: bridge
